export const LOGO = require('./images/icon/logo.png')
export const SOFTWAREVIETLOGO = require('./images/icon/logoSoftwareViet.png')
export const EXITICON = require('./images/icon/close.png')
export const AVATAR = require('./images/icon/avatar.png')
// export const EXITICON = require('./images/icon/exit.png')
export const WAITINGINVOICEICON = require('./images/icon/invoice.png')
export const RECIEVEDICON = require('./images/icon/export.png')
export const WAITINGINVOICEICONLIST = require('./images/icon/waiting-list.png')
export const DELIVERYMAN = require('./images/icon/delivery-man.png')
export const COMPLETEDTASK = require('./images/icon/completed-task.png')
export const FILE = require('./images/icon/file.png')
export const MAPICON = require('./images/icon/location.png')
export const HOMEICON = require('./images/icon/home.png')

export const SETTINGICON = require('./images/icon/user.png')
export const LOGOUTICON = require('./images/icon/logout.png')
export const Warring = require('./images/icon/warrring.png')
export const BarCode = require('./images/icon/barcode-scanner.png')
export const Box = require('./images/icon/box.png')
export const Search = require('./images/icon/search.png')
export const Receiver = require('./images/icon/receiver.png')
export const FILES = require('./images/icon/files.png')
export const Cancel = require('./images/icon/cancel.png')
export const Phone = require('./images/icon/telephone.png')
export const Check = require('./images/icon/check.png')
export const Exchange2 = require('./images/icon/exchange2.png')
export const Info = require('./images/icon/info.png')
export const EYE_HIDE = require('./images/icon/eye_hide.png')
export const EYE_SHOW = require('./images/icon/eye_showpass.jpg')
export const GHIM = require('./images/icon/pin.png')
//setting
export const CAIDAT = require('./images/icon/setting.png')
export const ICONRIGHT = require('./images/icon/right.png')
export const ICONFINGERPRINT = require('./images/icon/fingerprint.png')
export const RULES = require('./images/icon/rules.png')
export const ICONSHARE = require('./images/icon/share.png')
export const Finger = require('./images/icon/Finger.png')

